### ISSUE TITLE
Components of a SimplePoset

### ISSUE THREAD

**Issue by cscherrer** [scheinerman/SimpleGraphs.jl#2]
First, I'm really enjoying these packages, so thank you :)

I'm using a `SimplePoset` to track dependencies in a Bayesian model. For my current situation it's useful to cut some edges and then find the connected component containing a given node of the result.

I figured out that I can turn the poset into a `SimpleDigraph` with

```julia
julia> myposet.D
SimpleDigraph{Symbol} (n=7, m=10)
```

From here I'd like to be able to either...

- call `components`, or
- turn this `SimpleDigraph` into a `SimpleGraph` and then call `components` on that.

Neither of these seem to have been implemented. Do you know of a workaround?

**Comment by scheinerman** [comment]
Thanks for the post! You can turn directed graphs in to simple graphs with the `simplify` function:
```
julia> using SimpleGraphs

julia> P = DirectedPath(10)
SimpleDigraph{Int64} (n=10, m=9)

julia> G = simplify(P)
SimpleGraph{Int64} (n=10, m=9)
```
I think `simplify` has been part of `SimpleGraphs` for a while so you probably have it. Sorry if it's not documented!

I've made changes to `SimpleGraphs` but can't figure out how to register new versions since Julia 1.1. That means any very recent changes are not visible if you `add SimpleGraphs` in the package manager. If you `dev SimpleGraphs` then I think you'll have the latest ... but I'm not entirely sure how that works!

**Comment by cscherrer** [comment]
That works, thank you!

> I've made changes to SimpleGraphs but can't figure out how to register new versions since Julia 1.1

The biggest change I've seen in recent Pkg versions is that you now use `Project.toml` and `Manifest.toml` instead of `REQUIRE`. You don't edit them directly, but through `add`ing them.

That said, I haven't yet registered my main package. I'm happy to help once I've figured it out. Otherwise, I've found the community really helpful on Slack or Discourse for this sort of thing. I think your `SimpleWorld` ecosystem is a great addition to the Julia community. There are other graph libraries, but nothing else I know of for posets, or with such strong support for discrete math.

> If you dev SimpleGraphs then I think you'll have the latest

If you just want to use the latest (and not change anything to it) it's enough to `]add SimpleGraphs#master`.
